### PR TITLE
Bug 1112679 - Add local host info to the readme file

### PR DESCRIPTION
**Pull request by Gioyik**

### CODE REVIEW

**Comment by rbillings** [comment]
Looks good to me

**Comment by rbillings** [comment]
For reference this is for Bug 1112679: Add local host info to the readme file

**Comment by bobsilverberg** [comment]
Thanks for doing this, @Gioyik. I think there is a better solution to the problem though. Instead of adding that line to the `readme.md` file, we should update the `local.py-dist` in the `settings` folder to specify:

`BROWSERID_AUDIENCES = ['http://localhost:8000', 'http://127.0.0.1:8000']`

instead of:

`BROWSERID_AUDIENCES = ['http://localhost:8000']`

Do you want to try to make that change?

**Comment by Gioyik** [comment]
@bobsilverberg not problem. So, I need to revert the changes on the readme.md file?

**Comment by bobsilverberg** [comment]
@Gioyik Yes, we don't need the changes to the readme.md file.

**Comment by Gioyik** [comment]
@bobsilverberg done!

**Comment by bobsilverberg** [comment]
This is great, @Gioyik. Thanks for doing this!

Would you be able to squash the 3 commits that are currently in this branch into a single commit, after which I will merge the changes? For some info on doing this, please see https://wiki.mozilla.org/Web_Testing/Automation/CodeReviewProcess#Squashing_commits_before_merging_a_feature_branch

**Comment by Gioyik** [comment]
Commits squashed! Let me know if there's something I can do.

Thanks

**Comment by bobsilverberg** [comment]
Thanks @Gioyik. Great job!

**Pull request merged**
