### PR TITLE
updated legal page

### PR DESCRIPTION
**Pull request by swarnava**

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Thank you for the pull request, @swarnava. Could you please explain why this change is needed? Is this change documented somewhere? I notice that the current link works fine, although it does redirect to `mozilla.org/about/legal/`.

**Comment by swarnava** [comment]
This change is not a major fix, but i thought we should make link more up to date

**Comment by bobsilverberg** [comment]
Thanks @swarnava, I understand it is a minor change, but I just want to be sure it is necessary. How did you come to know that the link needed to be changed?

**Comment by swarnava** [comment]
Few months back, we were updating all link to redirected version, some examples are here:
*https://github.com/mozilla/remo/pull/712
*https://github.com/mozilla/mozillians/pull/912

& many more!

**Comment by rbillings** [comment]
The legal.html page does now redirect, and it looks like the /legal/ page was ported to bedrock here: https://github.com/mozilla/bedrock/pull/1988.

**Comment by bobsilverberg** [comment]
Okay, sounds reasonable to me. I'll merge it. Thanks @swarnava!

**Pull request merged**
