### PR TITLE
Fix Bug 1096418 - Task buttons are different sizes

### PR DESCRIPTION
**Pull request by tessie**

### CODE REVIEW

**Comment by tessie** [comment]
@bobsilverberg .ready to review

**Comment by bobsilverberg** [comment]
This does not fix the issue for me. I asked @rbillings in the bug where the issue remains, as I don't see it as much anymore. One place that it is very obvious, when you run the code in Chrome (and much less obvious, but also still present in Firefox), is on the Edit task screen. On this screen the "Cancel" and "Update task" buttons are different sizes, even with the changes in this pull request applied, so I think further changes are required.

In Chrome:
https://www.dropbox.com/s/tp9ydrjkroel2yg/Screenshot%202015-01-13%2009.33.12.png?dl=0

In Firefox:
https://www.dropbox.com/s/hywpx94ld91rabc/Screenshot%202015-01-13%2009.34.38.png?dl=0

**Comment by tessie** [comment]
@bobsilverberg .ready for another review.Now the heights of cancel and update tasks are 27.

**Comment by tessie** [comment]
Seems there is some difference in shadow effect.

**Comment by bobsilverberg** [comment]
This change seems to have fixed the issue with the "Cancel" and "Update task" buttons, so I'm going to merge it. I'll ask @rbillings to verify it in the bug.

**Comment by bobsilverberg** [comment]
@tessie I just need you to squash the commits first, please. :)

**Comment by tessie** [comment]
@bobsilverberg .squashed.Thank you for review

**Pull request merged**
