### PR TITLE
Adding gravatar support for profiles

### PR DESCRIPTION
**Pull request by jamonation**
Here's a PR for bug 1099301 -  Add avatars to user profile. It is just a gravatar toggle that uses the user's `bugzilla_email` for the hash.

### CODE REVIEW

**Comment by jamonation** [comment]
Ah this breaks tests that rely on `return self.get_queryset()` for the profile view. I'll fix that up shortly.

**Comment by rbillings** [comment]
@jamonation - are you still working on this?

**Comment by jamonation** [comment]
@rbillings I'm not sure where I left this. I think it was a selenium task that was breaking. I don't have that setup here to troubleshoot at the moment, but if you have some insight I could finish this off for sure.

**Comment by rbillings** [comment]
I'm afraid I don't have any details on what was broken or why. I'd need more info if you want help with a specific issue.

**Comment by rbillings** [comment]
I'm going to go ahead and close this out for now. You can re-open it again in the future if you'd like to continue working on it.

**Pull request closed without merging**
