### PR TITLE
Bug 1035800 - One time per user tasks

### PR DESCRIPTION
**Pull request by tessie**

### CODE REVIEW

**Comment by tessie** [comment]
@bobsilverberg .waiting for review

**Comment by bobsilverberg** [comment]
This looks good, @tessie, but we also need back-end logic to make sure that the rule is enforced. You updated the view code to disable the button, but there is nothing stopping a user from changing a form and starting a task manually. 

We need to update the `is_available_to_user` method in `Task` [1] to include logic to treat a task that is one time per user, and has already been completed by that user, as not available. In addition to that, some extra tests should be added for this method. You can see a bunch of existing tests for it at [2].

[1] https://github.com/mozilla/oneanddone/blob/master/oneanddone/tasks/models.py#L545 
[2] https://github.com/mozilla/oneanddone/blob/master/oneanddone/tasks/tests/test_models.py#L323-L361

**Comment by tessie** [comment]
@bobsilverberg .Updated the PR

**Comment by bobsilverberg** [comment]
Thanks for updating this, @tessie. This would be nice to land, but it now has merge conflicts because so many changes have been made to One and Done since you wrote this PR. Can you rebase this against the latest master branch to clean it up? Please let me know once that's done and then I'll review it again.

**Comment by bobsilverberg** [comment]
Also, we are now using Django migrations and not South migrations, so you'll need to create a new migration for this.

**Comment by rbillings** [comment]
@tessie this still needs a Django migration edit.

**Comment by rbillings** [comment]
@tessie - are you going to be able to finish this soon?

**Comment by rbillings** [comment]
Closing this due to lack of activity. We can re-open it if you want to continue working on it @tessie.

**Pull request closed without merging**
