### PR TITLE
Bug 1087266 - Add datetime for task execution in Task Activity view

### PR DESCRIPTION
**Pull request by tessie**
added the execution time activity_listing.html
@bobsilverberg .ready for review

### CODE REVIEW

**Comment by tessie** [comment]
@bobsilverberg .Thanks for the feedback.Fixed the editor

**Comment by bobsilverberg** [comment]
Looks good. Thanks for fixing it @tessie. :)

Could you please squash the commits now and then I will merge.

**Comment by tessie** [comment]
@bobsilverberg .squashed.But I am sorry again it came in the unexpected way with lots of commit messages

**Comment by bobsilverberg** [comment]
@tessie The single commit you have in there now looks fine. I only see the one commit message, so that's great. Whatever you did to remove all of the extra messages worked.

Good job!

**Pull request merged**
