### PR TITLE
Changing front page header to "Suggested First Tasks"

### PR DESCRIPTION
**Pull request by san13692**

### CODE REVIEW

**Comment by san13692** [comment]
According to bug 1032426 , changed front page header to "Suggested First Tasks"

**Comment by rbillings** [comment]
This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1032426, @bobsilverberg will you please confirm that the correct file has been updated?

**Comment by rbillings** [comment]
It was not marked clearly on the bug, but someone else started work on this bug last month [https://github.com/mozilla/oneanddone/pull/233] . Sorry for the confusion.

**Comment by bobsilverberg** [comment]
Yes, thanks for your efforts, @san13692, but this has already been fixed.

**Comment by san13692** [comment]
Thanx for feedback and no issue at all :)

**Pull request closed without merging**
