### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VarnaSuresh**
Update README.md to include step about running collectstatic, a pre-requisite for running functional tests on local site.

### CODE REVIEW

**Comment by rbillings** [comment]
R+

**Comment by rbillings** [comment]
@VarnaSuresh - this looks good, I'll go ahead and merge after it's been synced with the master branch.

**Comment by rbillings** [comment]
Please rebase with master.

**Comment by VarnaSuresh** [comment]
@rbillings Done.

**Comment by rbillings** [comment]
Thanks @VarnaSuresh !

**Pull request merged**
