### PR TITLE
Fixed Bug 1032426 - Unclear that front page displays only some tasks

### PR DESCRIPTION
**Pull request by tessie**
@glogiotatidis  or @akatsoulas  Please review my PR.https://bugzilla.mozilla.org/show_bug.cgi?id=1032426

Thank you in advance

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Thanks for doing this @tessie. It isn't quite perfect though. The bug only wanted us to change the heading for the home page, but this change makes the heading change on the home page [1] and also on the available tasks page [2] and the last listing page [3].

Can you please update it so the heading only changes on the home page [1]?

[1] http://127.0.0.1:8000/en-US/
[2] http://127.0.0.1:8000/en-US/tasks/available/
[3] http://127.0.0.1:8000/en-US/tasks/list/

**Comment by tessie** [comment]
@bobsilverberg .Please review my PR.I have bassed a the title as a context variable so that heading changes only on the home page

**Comment by bobsilverberg** [comment]
This is good @tessie, but I would suggest that just using the name `header` for the variable could be a bit confusing as a header could mean a number of things, and is often used to refer to a whole area of a page. I suggest changing the name of the variable to `task_list_heading`, which is much more specific.

**Comment by tessie** [comment]
@bobsilverberg .squashed

**Comment by tessie** [comment]
thanks for reviews

**Comment by bobsilverberg** [comment]
Excellent! Thanks @tessie!

**Pull request merged**
