### PR TITLE
Bug 1225172 - Create Recent Contributors module

### PR DESCRIPTION
**Pull request by bobsilverberg**

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@rbillings There was a problem with the review app for the previous PR. This one should work though. This one's at https://oneanddone-dev-pr-303.herokuapp.com/. I have added a couple of tasks, and started one of them. Please take a look at the Recent Contributors functionality in this review app.

**Comment by bobsilverberg** [comment]
@akatsoulas or @glogiotatidis r? please and thank you :)

**Comment by akatsoulas** [comment]
@bobsilverberg I can do a quick review tomorrow

**Comment by bobsilverberg** [comment]
Thanks @akatsoulas. Much appreciated!

**Comment by akatsoulas** [comment]
@bobsilverberg code looks good. I tested this locally and everything seems to be working fine. r+ :+1:

**Comment by bobsilverberg** [comment]
Thanks, as always, @akatsoulas !

**Comment by bobsilverberg** [comment]
This was closed via https://github.com/mozilla/oneanddone/commit/96a1810dc74ba2f1ca4231fe0140f220bbc3a56e

**Pull request closed without merging**
