### PR TITLE
Bug 1126344 - Add a link to Read the docs

### PR DESCRIPTION
**Pull request by tessie**

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Thanks for this, @tessie. @rbillings commented in the bug that she would like a button similar to what is on Moztrap, but is open to other ideas. I'm not sure that adding the link where you did will work for Rebecca, so I suggest you discuss this with her to see what she wants.

**Comment by tessie** [comment]
@bobsilverberg  sure.

**Comment by rbillings** [comment]
@tessie I would still like this as a button, if you're up for working on it.

**Comment by tessie** [comment]
@rbillings  Yea I would like to work on it

**Comment by rbillings** [comment]
@tessie - are you going to be able to finish this soon?

**Comment by tessie** [comment]
@rbillings  I would be busy.Sorry

**Comment by davehunt** [comment]
Thanks @tessie, @rbillings is this good enough for a merge, or should we work on it further?

**Comment by rbillings** [comment]
@davehunt I believe it could be merged once the conflicts are resolved.

**Comment by davehunt** [comment]
I've opened #352 after a rebase.

**Pull request closed without merging**
