### PR TITLE
Updated banner

### PR DESCRIPTION
**Pull request by rbillings**
Banner updated to describe retirement date plan.

### CODE REVIEW

**Comment by rbillings** [comment]
@karlht - please edit and/or merge when ready.

**Comment by karlht** [comment]
I am unsure whether this failure is due to recent GitHub review changes, or something that commit itself did.  I'm inclined to believe the former, but Travis is definitely unhappy.  :(

**Comment by stephendonner** [comment]
@karlht I logged in to Travis CI with my GitHub account and restarted the build -- all seems better now; you've got the green Merge... button /cc @rbillings

**Comment by karlht** [comment]
Thanks, Stephen.  Merged.

**Pull request merged**
