### PR TITLE
Fix Bug 1018373 - Add tooltip to Abandon and Complete task

### PR DESCRIPTION
**Pull request by tessie**

### CODE REVIEW

**Comment by tessie** [comment]
@bobsilverberg .Ready to review

**Comment by bobsilverberg** [comment]
@tessie This is backwards. The text on the button that you see on screen _should not_ have the `this` in it, and the tooltips, that are generated from the `title` attribute _should_ have the `this` in them.

**Comment by tessie** [comment]
@bobsilverberg .ready for review

**Comment by bobsilverberg** [comment]
Looks good. Thanks @tessie!

**Pull request merged**
