### PR TITLE
updated django to version 1.9.10

### PR DESCRIPTION
**Pull request by rbillings**

### CODE REVIEW

**Comment by rbillings** [comment]
Ready for review, @mozilla/web-qa-sorcerers

**Comment by stephendonner** [comment]
@rbillings doesn't the sha256 hash have to be changed, too?

It did in https://github.com/mozilla/oneanddone/pull/343/files when upgrading Django similarly

**Comment by rbillings** [comment]
Yes, I wonder why it didn't error out on my tests.... hmm. Will update.

**Comment by stephendonner** [comment]
Sorry - to add actual value to this PR, too, though I did run it successfully, as evidenced here:

oneanddone_web | System check identified no issues (0 silenced).
oneanddone_web | September 26, 2016 - 19:29:37
oneanddone_web | Django version 1.9.10, using settings 'oneanddone.settings'
oneanddone_web | Starting development server at http://0.0.0.0:8000/
oneanddone_web | Quit the server with CONTROL-C.

So, r+ pending the bump of the sha256 hash :-)

**Comment by rbillings** [comment]
Updated hash, tests pass, merging.

**Pull request merged**
