### PR TITLE
Fix Bug 1115909 - Menu does not open on One and Done

### PR DESCRIPTION
**Pull request by tessie**

### CODE REVIEW

**Comment by tessie** [comment]
@bobsilverberg .Ready for review

**Comment by bobsilverberg** [comment]
Hi @tessie. Sorry to take so long to review these open PRs. There was some major work to do to One and Done including updating to Django 1.7 and moving the site to Heroku. That is all done, so I am going to go back through all of the old PRs and review them.

This one won't really do what you want for a couple of reasons:
1. You have removed a bunch of JavaScript code that is actually needed for the Activity page, so those removals will break that page.
2. The new code you added just uses the class ` toggle` as a trigger for the event, but that is too general. This will cause the script to fire when anything with a `toggle` class is clicked on, and there are a number of items with that class (as you can in fact see from the code you removed).

Let me know if you want to work on this some more and address those problems.

**Comment by rbillings** [comment]
@tessie do you plan to finish up the suggested changes?

**Comment by rbillings** [comment]
@tessie - are you going to be able to finish this soon?

**Comment by tessie** [comment]
@rbillings  I am leaving this.A lots of issues occuring

**Comment by davehunt** [comment]
Closing this for someone else to work on - perhaps @karlht.

**Pull request closed without merging**
